# Spec for generating product.md
version: 1
name: generate_product_doc
owner: ai

description: |
  Generate a concise product brief describing the EDA pub/sub playground: vision,
  target users, problem/value, key use cases, success metrics, scope, non-goals, release plan.

output:
  target_file: product.md
  format: markdown

instructions: |
  Write product.md for the pubsub-eda repository. Keep it practical and succinct.
  Include the following sections with short paragraphs or lists:
  1. Vision
  2. Target Users
  3. Problem & Value Proposition
  4. Key Use Cases
  5. Success Metrics
  6. Scope (In/Out)
  7. Non-Goals
  8. Release Plan

  Style:
  - Keep headings at H1/H2 level
  - Prefer actionable, outcome-focused statements
  - Avoid marketing fluff; optimize for engineers

context_sources:
  - brief.md (optional)
  - architecture.md (optional)

allowed_tools:
  filesystem_read: true
  filesystem_write: false
  web_search: false
  shell_commands: false

acceptance_criteria:
  - File is valid Markdown with the sections listed above
  - No placeholders like TODO unless unavoidable
  - Tone is clear and engineering-focused
